# Generated by Django 4.2.28 on 2026-03-26 10:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0013_mocktestresult_status'),
        ('finance', '0002_expense_rename_created_at_payment_payment_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentfee',
            name='batch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='training.batch'),
        ),
    ]
