# Generated by Django 4.2.28 on 2026-04-16 15:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0018_announcement_target_role'),
        ('finance', '0007_payment_payment_type_alter_payment_accountant'),
    ]

    operations = [
        migrations.CreateModel(
            name='BatchFee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='training.batch')),
            ],
        ),
    ]
