# Generated by Django 4.2.28 on 2026-04-17 06:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0018_announcement_target_role'),
        ('finance', '0008_batchfee'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='batch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='training.batch'),
        ),
    ]
