# Generated by Django 4.2.28 on 2026-04-17 07:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_studentprofile_profile_image'),
        ('finance', '0009_invoice_batch'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='student',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.studentprofile'),
        ),
    ]
