# Generated by Django 4.2.28 on 2026-04-17 12:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('finance', '0011_alter_invoice_student'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FeeType',
        ),
        migrations.AddField(
            model_name='invoice',
            name='invoice_type',
            field=models.CharField(blank=True, choices=[('case', 'Case'), ('student', 'Student')], default='case', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='payment',
            name='accountant',
            field=models.ForeignKey(blank=True, limit_choices_to={'role': 'ACCOUNTANT'}, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='StudentFee',
        ),
    ]
