# Generated by Django 4.2.28 on 2026-04-19 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0012_delete_feetype_invoice_invoice_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='receipt',
            field=models.FileField(blank=True, null=True, upload_to='expenses/'),
        ),
    ]
