# Generated by Django 4.2.28 on 2026-05-06 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0013_expense_receipt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('paid', 'Paid'), ('partial', 'Partial'), ('overdue', 'Overdue')], default='pending', max_length=20),
        ),
    ]
