# Generated by Django 4.2.28 on 2026-03-18 16:29

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cases', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='case',
            name='junior_advocate',
        ),
        migrations.AddField(
            model_name='case',
            name='junior_advocates',
            field=models.ManyToManyField(blank=True, related_name='junior_cases', to=settings.AUTH_USER_MODEL),
        ),
    ]
