# Generated by Django 4.2.28 on 2026-03-20 06:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0003_remove_case_junior_advocate_case_junior_advocates'),
    ]

    operations = [
        migrations.AddField(
            model_name='hearing',
            name='junior_notes',
            field=models.TextField(blank=True),
        ),
        migrations.CreateModel(
            name='HearingNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('hearing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hearing_notes', to='cases.hearing')),
            ],
        ),
        migrations.CreateModel(
            name='HearingDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('document_type', models.CharField(max_length=50)),
                ('file', models.FileField(upload_to='hearing_docs/')),
                ('status', models.CharField(default='Pending', max_length=50)),
                ('hearing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='cases.hearing')),
            ],
        ),
        migrations.CreateModel(
            name='HearingChecklist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('completed', models.BooleanField(default=False)),
                ('hearing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checklist_items', to='cases.hearing')),
            ],
        ),
    ]
