# Generated by Django 4.2.28 on 2026-03-22 11:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cases', '0005_caseassignment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='case',
            name='junior_advocates',
        ),
        migrations.AlterField(
            model_name='caseassignment',
            name='junior',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='caseassignment',
            unique_together={('case', 'junior')},
        ),
    ]
