# Generated by Django 4.2.28 on 2026-03-22 11:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cases', '0006_remove_case_junior_advocates_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='caseassignment',
            name='case',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='cases.case'),
        ),
        migrations.AlterField(
            model_name='caseassignment',
            name='junior',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
