# Generated by Django 4.2.28 on 2026-03-27 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0007_alter_caseassignment_case_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='caseassignment',
            name='responsibility',
            field=models.TextField(),
        ),
    ]
