# Generated by Django 4.2.28 on 2026-03-28 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0008_alter_caseassignment_responsibility'),
    ]

    operations = [
        migrations.AlterField(
            model_name='case',
            name='status',
            field=models.CharField(choices=[('Ongoing', 'Ongoing'), ('Critical', 'Critical'), ('Won', 'Won'), ('Lost', 'Lost'), ('Disposed', 'Disposed')], default='Ongoing', max_length=20),
        ),
    ]
