# Generated by Django 4.2.28 on 2026-03-19 05:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='reporting_senior',
            field=models.ForeignKey(blank=True, limit_choices_to={'role__iexact': 'senior'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='junior_team', to=settings.AUTH_USER_MODEL),
        ),
    ]
