# Generated by Django 4.2.28 on 2026-03-22 13:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_user_reporting_senior'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='reporting_senior',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='supervised_juniors', to=settings.AUTH_USER_MODEL),
        ),
    ]
