# Generated by Django 4.2.28 on 2026-05-06 10:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0002_document_uploaded_by'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Policy',
        ),
    ]
