# Generated by Django 4.2.28 on 2026-04-04 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='auditlog',
            name='entity_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='auditlog',
            name='entity_type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
